create table if not exists public.clan_member_applications (
  id bigint generated by default as identity primary key,
  username text not null,
  discord_tag text,
  password_hash text,
  avatar_url text,
  game text not null default 'Minecraft Java',
  rank text not null default 'BVR',
  preferred_tryout boolean not null default false,
  clip_url text,
  status text not null default 'Pending',
  created_at timestamptz not null default now()
);

alter table public.clan_member_applications add column if not exists password_hash text;
alter table public.clan_member_applications add column if not exists avatar_url text;
alter table public.clan_member_applications add column if not exists game text not null default 'Minecraft Java';
alter table public.clan_member_applications add column if not exists preferred_tryout boolean not null default false;
alter table public.clan_member_applications add column if not exists clip_url text;

create table if not exists public.clan_members (
  id bigint generated by default as identity primary key,
  username text not null unique,
  discord_tag text,
  avatar_url text,
  game text not null default 'Minecraft Java',
  rank text not null default 'BVR',
  ranking_number integer check (ranking_number is null or ranking_number > 0),
  last_seen timestamptz,
  created_at timestamptz not null default now()
);

alter table public.clan_members add column if not exists avatar_url text;
alter table public.clan_members add column if not exists game text not null default 'Minecraft Java';
alter table public.clan_members add column if not exists ranking_number integer;
alter table public.clan_members add column if not exists last_seen timestamptz;

drop index if exists clan_members_ranking_number_unique;
create unique index if not exists clan_members_game_ranking_number_unique
on public.clan_members (game, ranking_number)
where ranking_number is not null;

create table if not exists public.clips (
  id bigint generated by default as identity primary key,
  author_username text not null,
  caption text not null default '',
  clip_url text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.clip_comments (
  id bigint generated by default as identity primary key,
  clip_id bigint not null references public.clips(id) on delete cascade,
  author_username text not null,
  comment_text text not null,
  created_at timestamptz not null default '',
  created_at timestamptz not null default now()
);

insert into storage.buckets (id, name, public)
values ('black-velvet-media', 'black-velvet-media', true)
on conflict (id) do update set public = true;

alter table public.clan_member_applications enable row level security;
alter table public.clan_members enable row level security;
alter table public.clips enable row level security;
alter table public.clip_comments enable row level security;

drop policy if exists "Public can read clan applications" on public.clan_member_applications;
drop policy if exists "Public can submit clan applications" on public.clan_member_applications;
drop policy if exists "Public can update clan applications" on public.clan_member_applications;
create policy "Public can read clan applications" on public.clan_member_applications for select to anon, authenticated using (true);
create policy "Public can submit clan applications" on public.clan_member_applications for insert to anon, authenticated with check (true);
create policy "Public can update clan applications" on public.clan_member_applications for update to anon, authenticated using (true) with check (true);

drop policy if exists "Public can read clan members" on public.clan_members;
drop policy if exists "Public can create clan members" on public.clan_members;
drop policy if exists "Public can update clan members" on public.clan_members;
drop policy if exists "Public can delete clan members" on public.clan_members;
create policy "Public can read clan members" on public.clan_members for select to anon, authenticated using (true);
create policy "Public can create clan members" on public.clan_members for insert to anon, authenticated with check (true);
create policy "Public can update clan members" on public.clan_members for update to anon, authenticated using (true) with check (true);
create policy "Public can delete clan members" on public.clan_members for delete to anon, authenticated using (true);

drop policy if exists "Public can read clips" on public.clips;
drop policy if exists "Public can create clips" on public.clips;
drop policy if exists "Public can update clips" on public.clips;
drop policy if exists "Public can delete clips" on public.clips;
create policy "Public can read clips" on public.clips for select to anon, authenticated using (true);
create policy "Public can create clips" on public.clips for insert to anon, authenticated with check (true);
create policy "Public can update clips" on public.clips for update to anon, authenticated using (true) with check (true);
create policy "Public can delete clips" on public.clips for delete to anon, authenticated using (true);

drop policy if exists "Public can read clip comments" on public.clip_comments;
drop policy if exists "Public can create clip comments" on public.clip_comments;
drop policy if exists "Public can delete clip comments" on public.clip_comments;
create policy "Public can read clip comments" on public.clip_comments for select to anon, authenticated using (true);
create policy "Public can create clip comments" on public.clip_comments for insert to anon, authenticated with check (true);
create policy "Public can delete clip comments" on public.clip_comments for delete to anon, authenticated using (true);

drop policy if exists "Public can view Black Velvet media" on storage.objects;
drop policy if exists "Public can upload Black Velvet media" on storage.objects;
drop policy if exists "Public can delete Black Velvet media" on storage.objects;
create policy "Public can view Black Velvet media"
on storage.objects for select to anon, authenticated
using (bucket_id = 'black-velvet-media');

create policy "Public can upload Black Velvet media"
on storage.objects for insert to anon, authenticated
with check (bucket_id = 'black-velvet-media');

create policy "Public can delete Black Velvet media"
on storage.objects for delete to anon, authenticated
using (bucket_id = 'black-velvet-media');
