create table if not exists public.clan_member_applications (
  id bigint generated by default as identity primary key,
  username text not null,
  discord_tag text,
  rank text not null default 'BVR',
  preferred_tryout boolean not null default false,
  clip_url text,
  status text not null default 'Pending',
  created_at timestamptz not null default now()
);

alter table public.clan_member_applications
add column if not exists preferred_tryout boolean not null default false;

alter table public.clan_member_applications
add column if not exists clip_url text;

create table if not exists public.clan_members (
  id bigint generated by default as identity primary key,
  username text not null unique,
  discord_tag text,
  rank text not null default 'BVR',
  ranking_number integer unique check (ranking_number > 0),
  created_at timestamptz not null default now()
);

alter table public.clan_members
add column if not exists ranking_number integer;

alter table public.clan_members
drop constraint if exists clan_members_ranking_number_check;

alter table public.clan_members
add constraint clan_members_ranking_number_check
check (ranking_number is null or ranking_number > 0);

create unique index if not exists clan_members_ranking_number_unique
on public.clan_members (ranking_number)
where ranking_number is not null;

alter table public.clan_member_applications enable row level security;
alter table public.clan_members enable row level security;

drop policy if exists "Public can read clan applications" on public.clan_member_applications;
drop policy if exists "Public can submit clan applications" on public.clan_member_applications;
drop policy if exists "Public can update clan applications" on public.clan_member_applications;

create policy "Public can read clan applications"
on public.clan_member_applications
for select to anon, authenticated
using (true);

create policy "Public can submit clan applications"
on public.clan_member_applications
for insert to anon, authenticated
with check (true);

create policy "Public can update clan applications"
on public.clan_member_applications
for update to anon, authenticated
using (true)
with check (true);

drop policy if exists "Public can read clan members" on public.clan_members;
drop policy if exists "Public can create clan members" on public.clan_members;
drop policy if exists "Public can update clan members" on public.clan_members;
drop policy if exists "Public can delete clan members" on public.clan_members;

create policy "Public can read clan members"
on public.clan_members
for select to anon, authenticated
using (true);

create policy "Public can create clan members"
on public.clan_members
for insert to anon, authenticated
with check (true);

create policy "Public can update clan members"
on public.clan_members
for update to anon, authenticated
using (true)
with check (true);

create policy "Public can delete clan members"
on public.clan_members
for delete to anon, authenticated
using (true);
