create table if not exists public.system_errors (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  source text,
  message text not null,
  stack_trace text,
  page_url text,
  username text,
  user_role text,
  device_hex text,
  browser text
);

alter table public.system_errors enable row level security;

drop policy if exists "Anyone can report system errors" on public.system_errors;
drop policy if exists "Anyone can read system errors" on public.system_errors;
drop policy if exists "Anyone can clear system errors" on public.system_errors;

create policy "Anyone can report system errors"
on public.system_errors
for insert
to anon, authenticated
with check (true);

create policy "Anyone can read system errors"
on public.system_errors
for select
to anon, authenticated
using (true);

create policy "Anyone can clear system errors"
on public.system_errors
for delete
to anon, authenticated
using (true);

grant select, insert, delete on public.system_errors to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'system_errors'
  ) then
    alter publication supabase_realtime add table public.system_errors;
  end if;
end $$;
