create table if not exists public.system_errors (
  id bigint generated by default as identity primary key,
  source text not null default 'Unknown',
  message text not null,
  stack_trace text,
  page_url text,
  username text,
  user_role text,
  device_hex text,
  browser text,
  created_at timestamptz not null default now()
);

alter table public.system_errors enable row level security;

drop policy if exists "Public can create system errors" on public.system_errors;
drop policy if exists "Public can read system errors" on public.system_errors;
drop policy if exists "Public can delete system errors" on public.system_errors;

create policy "Public can create system errors"
on public.system_errors
for insert
to anon, authenticated
with check (true);

create policy "Public can read system errors"
on public.system_errors
for select
to anon, authenticated
using (true);

create policy "Public can delete system errors"
on public.system_errors
for delete
to anon, authenticated
using (true);

alter publication supabase_realtime add table public.system_errors;
